### ISSUE TITLE
Syntax errors

### ISSUE THREAD

**Issue by kalymnred** [Dolibarr/dolibarr-module-template#23]
There are some syntax errors in some files generated with build_class_from_table.php

ModuleName_list.php: Call to undefined function dol_escpae_htmltag()

ModuleName.class.php @create: Some commas missing at the insert into query

**Comment by rdoursenaud** [comment]
```build_class_from_table.php``` is part of Dolibarr, not the module template.
Please report the bug at https://github.com/Dolibarr/dolibarr/issues.
Thanks.
